In [26]:
import pandas as pd 
import numpy as np 

df = pd.read_csv('data/raw/owid-co2-data.csv')

In [27]:

df_post_1950 = df[df["year"] >= 1950].reset_index(drop=True)

missing_post_1950 = df_post_1950.isna().mean().sort_values(ascending=False)

cols_to_drop = missing_post_1950[missing_post_1950 > 0.5].index.tolist()

df = df_post_1950.drop(columns=cols_to_drop)

In [28]:
df

,country,year,iso_code,population,gdp,cement_co2,cement_co2_per_capita,co2,co2_growth_abs,co2_growth_prct,...,share_global_flaring_co2,share_global_luc_co2,share_global_oil_co2,share_of_temperature_change_from_ghg,temperature_change_from_ch4,temperature_change_from_co2,temperature_change_from_ghg,temperature_change_from_n2o,total_ghg,total_ghg_excluding_lucf
0,Afghanistan,1950,AFG,7776182.0,9.421400e+09,0.000,0.000,0.084,0.070,475.000,...,NaN,0.117,0.004,0.128,0.000,0.000,0.001,0.0,19.447,1.453
1,Afghanistan,1951,AFG,7879343.0,9.692280e+09,0.000,0.000,0.092,0.007,8.696,...,NaN,0.125,0.004,0.128,0.000,0.000,0.001,0.0,20.458,1.473
2,Afghanistan,1952,AFG,7987783.0,1.001733e+10,0.000,0.000,0.092,0.000,0.000,...,NaN,0.140,0.003,0.128,0.000,0.000,0.001,0.0,21.356,1.484
3,Afghanistan,1953,AFG,8096703.0,1.063052e+10,0.000,0.000,0.106,0.015,16.000,...,NaN,0.154,0.004,0.128,0.000,0.000,0.001,0.0,22.361,1.517
4,Afghanistan,1954,AFG,8207953.0,1.086636e+10,0.000,0.000,0.106,0.000,0.000,...,NaN,0.158,0.003,0.128,0.000,0.000,0.001,0.0,23.256,1.534
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18759,Zimbabwe,2019,ZWE,15271377.0,2.514642e+10,0.473,0.031,10.263,-0.942,-8.411,...,0.0,0.252,0.030,0.106,0.001,0.001,0.002,0.0,34.348,17.531
18760,Zimbabwe,2020,ZWE,15526888.0,2.317871e+10,0.496,0.032,8.495,-1.768,-17.231,...,0.0,0.260,0.028,0.105,0.001,0.001,0.002,0.0,31.323,15.775
18761,Zimbabwe,2021,ZWE,15797220.0,2.514009e+10,0.531,0.034,10.204,1.709,20.120,...,0.0,0.241,0.032,0.104,0.001,0.001,0.002,0.0,33.549,17.599
18762,Zimbabwe,2022,ZWE,16069061.0,2.590159e+10,0.531,0.033,10.425,0.221,2.169,...,0.0,0.227,0.028,0.103,0.001,0.001,0.002,0.0,33.772,17.910
18763,Zimbabwe,2023,ZWE,16340829.0,NaN,0.531,0.032,11.164,0.739,7.090,...,0.0,0.204,0.028,0.102,0.001,0.001,0.002,0.0,33.955,18.608

In [29]:
df = df[df['iso_code'].str.len() ==3].drop(columns='iso_code')

df

,country,year,population,gdp,cement_co2,cement_co2_per_capita,co2,co2_growth_abs,co2_growth_prct,co2_including_luc,...,share_global_flaring_co2,share_global_luc_co2,share_global_oil_co2,share_of_temperature_change_from_ghg,temperature_change_from_ch4,temperature_change_from_co2,temperature_change_from_ghg,temperature_change_from_n2o,total_ghg,total_ghg_excluding_lucf
0,Afghanistan,1950,7776182.0,9.421400e+09,0.000,0.000,0.084,0.070,475.000,7.316,...,NaN,0.117,0.004,0.128,0.000,0.000,0.001,0.0,19.447,1.453
1,Afghanistan,1951,7879343.0,9.692280e+09,0.000,0.000,0.092,0.007,8.696,8.264,...,NaN,0.125,0.004,0.128,0.000,0.000,0.001,0.0,20.458,1.473
2,Afghanistan,1952,7987783.0,1.001733e+10,0.000,0.000,0.092,0.000,0.000,9.192,...,NaN,0.140,0.003,0.128,0.000,0.000,0.001,0.0,21.356,1.484
3,Afghanistan,1953,8096703.0,1.063052e+10,0.000,0.000,0.106,0.015,16.000,10.269,...,NaN,0.154,0.004,0.128,0.000,0.000,0.001,0.0,22.361,1.517
4,Afghanistan,1954,8207953.0,1.086636e+10,0.000,0.000,0.106,0.000,0.000,11.137,...,NaN,0.158,0.003,0.128,0.000,0.000,0.001,0.0,23.256,1.534
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18759,Zimbabwe,2019,15271377.0,2.514642e+10,0.473,0.031,10.263,-0.942,-8.411,19.807,...,0.0,0.252,0.030,0.106,0.001,0.001,0.002,0.0,34.348,17.531
18760,Zimbabwe,2020,15526888.0,2.317871e+10,0.496,0.032,8.495,-1.768,-17.231,17.430,...,0.0,0.260,0.028,0.105,0.001,0.001,0.002,0.0,31.323,15.775
18761,Zimbabwe,2021,15797220.0,2.514009e+10,0.531,0.034,10.204,1.709,20.120,18.752,...,0.0,0.241,0.032,0.104,0.001,0.001,0.002,0.0,33.549,17.599
18762,Zimbabwe,2022,16069061.0,2.590159e+10,0.531,0.033,10.425,0.221,2.169,18.447,...,0.0,0.227,0.028,0.103,0.001,0.001,0.002,0.0,33.772,17.910
18763,Zimbabwe,2023,16340829.0,NaN,0.531,0.032,11.164,0.739,7.090,18.567,...,0.0,0.204,0.028,0.102,0.001,0.001,0.002,0.0,33.955,18.608

In [30]:
numeric_cols = df.drop(columns='country')

In [31]:
numeric_cols = numeric_cols.columns.to_list()

In [32]:
df  = df.groupby('country')[numeric_cols].ffill().bfill()

In [33]:
df

,year,population,gdp,cement_co2,cement_co2_per_capita,co2,co2_growth_abs,co2_growth_prct,co2_including_luc,co2_including_luc_growth_abs,...,share_global_flaring_co2,share_global_luc_co2,share_global_oil_co2,share_of_temperature_change_from_ghg,temperature_change_from_ch4,temperature_change_from_co2,temperature_change_from_ghg,temperature_change_from_n2o,total_ghg,total_ghg_excluding_lucf
0,1950,7776182.0,9.421400e+09,0.000,0.000,0.084,0.070,475.000,7.316,1.066,...,0.107,0.117,0.004,0.128,0.000,0.000,0.001,0.0,19.447,1.453
1,1951,7879343.0,9.692280e+09,0.000,0.000,0.092,0.007,8.696,8.264,0.948,...,0.107,0.125,0.004,0.128,0.000,0.000,0.001,0.0,20.458,1.473
2,1952,7987783.0,1.001733e+10,0.000,0.000,0.092,0.000,0.000,9.192,0.928,...,0.107,0.140,0.003,0.128,0.000,0.000,0.001,0.0,21.356,1.484
3,1953,8096703.0,1.063052e+10,0.000,0.000,0.106,0.015,16.000,10.269,1.077,...,0.107,0.154,0.004,0.128,0.000,0.000,0.001,0.0,22.361,1.517
4,1954,8207953.0,1.086636e+10,0.000,0.000,0.106,0.000,0.000,11.137,0.869,...,0.107,0.158,0.003,0.128,0.000,0.000,0.001,0.0,23.256,1.534
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18759,2019,15271377.0,2.514642e+10,0.473,0.031,10.263,-0.942,-8.411,19.807,-1.695,...,0.000,0.252,0.030,0.106,0.001,0.001,0.002,0.0,34.348,17.531
18760,2020,15526888.0,2.317871e+10,0.496,0.032,8.495,-1.768,-17.231,17.430,-2.377,...,0.000,0.260,0.028,0.105,0.001,0.001,0.002,0.0,31.323,15.775
18761,2021,15797220.0,2.514009e+10,0.531,0.034,10.204,1.709,20.120,18.752,1.322,...,0.000,0.241,0.032,0.104,0.001,0.001,0.002,0.0,33.549,17.599
18762,2022,16069061.0,2.590159e+10,0.531,0.033,10.425,0.221,2.169,18.447,-0.305,...,0.000,0.227,0.028,0.103,0.001,0.001,0.002,0.0,33.772,17.910
18763,2023,16340829.0,2.590159e+10,0.531,0.032,11.164,0.739,7.090,18.567,0.120,...,0.000,0.204,0.028,0.102,0.001,0.001,0.002,0.0,33.955,18.608

In [34]:
df.isna().sum()

year                           0
population                     0
gdp                            0
cement_co2                     0
cement_co2_per_capita          0
                              ..
temperature_change_from_co2    0
temperature_change_from_ghg    0
temperature_change_from_n2o    0
total_ghg                      0
total_ghg_excluding_lucf       0
Length: 61, dtype: int64

In [35]:
df.to_csv('clean.csv', index=False)

In [36]:
df

,year,population,gdp,cement_co2,cement_co2_per_capita,co2,co2_growth_abs,co2_growth_prct,co2_including_luc,co2_including_luc_growth_abs,...,share_global_flaring_co2,share_global_luc_co2,share_global_oil_co2,share_of_temperature_change_from_ghg,temperature_change_from_ch4,temperature_change_from_co2,temperature_change_from_ghg,temperature_change_from_n2o,total_ghg,total_ghg_excluding_lucf
0,1950,7776182.0,9.421400e+09,0.000,0.000,0.084,0.070,475.000,7.316,1.066,...,0.107,0.117,0.004,0.128,0.000,0.000,0.001,0.0,19.447,1.453
1,1951,7879343.0,9.692280e+09,0.000,0.000,0.092,0.007,8.696,8.264,0.948,...,0.107,0.125,0.004,0.128,0.000,0.000,0.001,0.0,20.458,1.473
2,1952,7987783.0,1.001733e+10,0.000,0.000,0.092,0.000,0.000,9.192,0.928,...,0.107,0.140,0.003,0.128,0.000,0.000,0.001,0.0,21.356,1.484
3,1953,8096703.0,1.063052e+10,0.000,0.000,0.106,0.015,16.000,10.269,1.077,...,0.107,0.154,0.004,0.128,0.000,0.000,0.001,0.0,22.361,1.517
4,1954,8207953.0,1.086636e+10,0.000,0.000,0.106,0.000,0.000,11.137,0.869,...,0.107,0.158,0.003,0.128,0.000,0.000,0.001,0.0,23.256,1.534
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18759,2019,15271377.0,2.514642e+10,0.473,0.031,10.263,-0.942,-8.411,19.807,-1.695,...,0.000,0.252,0.030,0.106,0.001,0.001,0.002,0.0,34.348,17.531
18760,2020,15526888.0,2.317871e+10,0.496,0.032,8.495,-1.768,-17.231,17.430,-2.377,...,0.000,0.260,0.028,0.105,0.001,0.001,0.002,0.0,31.323,15.775
18761,2021,15797220.0,2.514009e+10,0.531,0.034,10.204,1.709,20.120,18.752,1.322,...,0.000,0.241,0.032,0.104,0.001,0.001,0.002,0.0,33.549,17.599
18762,2022,16069061.0,2.590159e+10,0.531,0.033,10.425,0.221,2.169,18.447,-0.305,...,0.000,0.227,0.028,0.103,0.001,0.001,0.002,0.0,33.772,17.910
18763,2023,16340829.0,2.590159e+10,0.531,0.032,11.164,0.739,7.090,18.567,0.120,...,0.000,0.204,0.028,0.102,0.001,0.001,0.002,0.0,33.955,18.608

In [ ]:
cols = ['year', 'population', 'gdp', 'cement_co2_per_capita', 'co2',
       'co2_growth_abs', 'co2_including_luc_growth_abs',
       'co2_including_luc_per_capita', 'co2_including_luc_per_gdp',
       'co2_including_luc_per_unit_energy', 'co2_per_capita', 'co2_per_gdp',
       'co2_per_unit_energy', 'coal_co2_per_capita',
       'energy_per_capita', 'flaring_co2_per_capita',
       'ghg_excluding_lucf_per_capita', 'ghg_per_capita',
       'land_use_change_co2_per_capita', 'methane_per_capita',
       'nitrous_oxide_per_capita', 'oil_co2_per_capita',
       'primary_energy_consumption',
       'temperature_change_from_co2', 'temperature_change_from_ghg',
       'temperature_change_from_n2o', 'total_ghg', 'total_ghg_excluding_lucf']
'consumption_co2_per_capita', 'consumption_co2_per_gdp', 'energy_per_gdp', 'gas_co2_per_capita', 'other_co2_per_capita'
final_df = df[cols]
final_df

KeyError: "['consumption_co2_per_capita', 'consumption_co2_per_gdp', 'energy_per_gdp', 'gas_co2_per_capita', 'other_co2_per_capita'] not in index"